language: java

jdk:
  - oraclejdk11

addons:
  sonarcloud:
    organization: desapp-grupo-d-012021
    token:
      secure: l7JI4BXUG5QIc3mNiw8iBLAMvd3V+ng4PEXLzU9k9oD2M2lf/pS74rHvh3x571ck4MTkH+FPWUGnAknpmky2kfVILpTQgNKUveW1ceiAkQot/Cppu276EMmjvfoRRcCfXqAl+HqFujmTML9cZH3/QKHafhfe6jje0EJOkeqpNVJIMgCYrRot9uXImN8AIvrWLGW3tUmG/vOdnupHig5SikVgNo90q32Hw3HbO3JXIHoK2SPxaFpml/C2jJvxA6feEhXwVWdPGrERbNvHDoNbsnDFegk9fvQGnJBAyUA017bU+SzdwJYOnYlkV9Qq5ey8QJsfkvM/oEOFBy2ybAYjjTiuX76omjLRrfElLe+/QuXhB0ZO/xurkrqO3/M4BtklTM+u6E9u4WMJegUNUs/q+CvVfp6KYM/ZX1/jfCPxyWgycaktI3YZDCkbZ+qXgNa0tZRI/JT8WSsuslMm6OOP0+VfI/cuiIIWocHZhk6/MpxnQwNNSeURHqgNanYTxkO5u+zjh/+3Qbq0Xm8MnDt8gw2ji3iB+dXzxMDZFkuA4pfKvYq4b9qespUHgDscbJj1tVQnCuPxa79oRShQZjds+lQY5mb5jzqy1YrFrIb/RuRapFD0qpLvjGaFkFjYkZfXTVEYU2h0MYbNvYfLqcBIu12XskVrdYJnnSBjOL3JVuo=

before_install:
  - chmod +x gradlew
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

script:
  - "./gradlew check"
  - "./gradlew jacocoTestReport"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "./gradlew sonarqube"

deploy:
  provider: heroku
  api_key:
    secure: KBkVU+Ej9Lue4ARaK8H/p+FPg14mm/thJ17ePxmcPsA6g/hi1wZmpFFRhP9zTE31HMk/2AMZRtiLfftHVXx/gnZ16qrcunE0dISoUFbxkmMhUDtRjVZBrt1Qpohf5bhfCXccBC2IbQNrME9g4M10vQrMlBLKhLEZb+/jLZBXs35Ago5GQnBw5RVcfAwCA2uN3a4hGebT8R0LTq9NkgYRUmAjcDQ842qg8uE1habBTFpn9haYIUG9gvjJqqfmSB4Ot7AxXHQsnapeeqbe/nGwiFULnfohszsWdeis7TCXUgz+Fvr4Ln9Ll+T8TrBtqL+8nCnzj0qd8SvgFHosI0ZqyiO3nXSxF/0PHWMwkRLpNQmXf1JicINf+/7qLnj7nG+Ln11sKA77UeFhtBP5v1MPvUkD29V3ffH+JoC8ifYaAFtTtS8dMPEPOziVl3wy9GUUAXBaVJaDNggcWwjaAtDMCZa1DLpbzBEkH2ysWQmCtHdOQYmcTPww79Sqt/ZbY5tEvhRq421TotH4WVf3rfWqbNB1k3iFRI5tbattBBv2RjA61wQbC9X7AbtMxPgGJZquS72M3gFtAJF4W9QjSh+HDiMvZOVndzob0mb9EboC1vnBFGTB+6SyJP/usjb7hNnBeFDe/3e4BCL56eQUE/bg6Yh+Tg4bWHvvl4VMdM8TLig=

  app: resena-backend
  on:
    repo: desapp-grupo-D-012021/backend
    branch: main
